### ISSUE TITLE
Multiple ST-Nmea converters on single network

### ISSUE THREAD

**Issue by ckcrs** [AK-Homberger/Seatalk-Autopilot-Remote-Control#1]
Hi,
As a novice follower, just ordered a pro micro 5V to try this with my existing SignalK and ST network setup to control ST6002 ( trying to control AP via SignalK through RPi-ProMicro serial communication)
I would like to understand if adding this tool to ST network in addition an existing ST_NMEA convertor will create any control/collision issues?
Thanks and regards,
Sancan
PS: Although not an issue, cannot find any other means to ask, sorry if inconvinient.

**Comment by AK-Homberger** [comment]
Hi,
Simply connect it to the Seatalk Network. It will work. There is no problem with an additional ST_NMEA converter.

Regards,
Andreas

**Comment by ckcrs** [comment]
Hello Andreas,
Thank you for your reply.
I will try when the parts completed then hope to adopt for use as a
controller with Signal K on serial connection between RPi and ProMicro.
Regards,
Sancan
