### ISSUE TITLE
Tested device list

### ISSUE THREAD

**Issue by jekil** [AK-Homberger/Seatalk-Autopilot-Remote-Control#12]
Readme mentions how the project was tested on several devices.
It would be nice to include a list of them.

Thanks so much for this awesome project.

**Comment by AK-Homberger** [comment]
What devices you are referring too? Autopilots? MFDs? In general it will work with all Seatalk1 based autopilots. On newer MFDs the beep will not work.

**Comment by jekil** [comment]
Autopilots.

**Comment by AK-Homberger** [comment]
All autopilots compatible with the original remote controller (S110, Smart Controller) should work. Either directly with Seatalk or with the converter also SeatalkNG.
