### ISSUE TITLE
SEATALK communication - datagram content

### ISSUE THREAD

**Issue by janokylaszlo** [AK-Homberger/Seatalk-Autopilot-Remote-Control#14]
Thanks to some good advice I finally managed to solve the "SERIAL_9N1" problem, the software compiled successfully and runs fine. The SEATALK communication works (at least according to the oscilloscope screen) - but my ST2000+ steering does not respond to any data packets. That's what I tried: 
dg[] = 186 0 5 fa
dg[] = 186 1 5 fa
dg[] = 186 11 5 fa
dg[] = 186 21 5 fa
dg[] = 186 0 45 ba
dg[] = 186 1 45 ba
dg[] = 186 11 45 ba
dg[] = 186 21 45 ba
dg[] = 186 0 9 f6
dg[] = 186 1 9 f6
dg[] = 186 11 9 f6
dg[] = 186 21 9 f6
dg[] = 186 0 80 7f
dg[] = 186 1 80 7f
dg[] = 186 11 80 7f
dg[] = 186 21 80 7f
I could find no other descriptions, only this one:
http://www.thomasknauf.de/rap/seatalk2.htm (was quoted in several places).
Does anyone have any suggestions on what else I could try? Or what else could be the problem?

Thanks a lot!
LJ

**Comment by AK-Homberger** [comment]
I'm no aware of any othe ressources for additional codes.
