### ISSUE TITLE
READ SEALTALK DATA with USB

### ISSUE THREAD

**Issue by ignamendi21** [AK-Homberger/Seatalk-Autopilot-Remote-Control#15]
Hello, Using this project, would it be posible to read the seatalk data using the usb and defining se serial comunicaction (nm0183) in openplotter/signalK¿??

**Comment by AK-Homberger** [comment]
You can read Seatlak messages in the same way as I did for the wind data for other codes. Then you can assemble NMEA 0183 messges and send the result either via USB-Serial or with another pin (e.g. with the Softwareserial library).
