### ISSUE TITLE
Seatalk codes X-value

### ISSUE THREAD

**Issue by TomHW** [AK-Homberger/Seatalk-Autopilot-Remote-Control#2]
Hi Andreas,
in the ArduinoPilotMicro433WindNG.ino I found the codes of the RF remote control and I compared it to the codes from Thomas Knauf’s website. I got the impression that you are sending the codes of the Autopilot (X=2) and not the codes of the remote control (X=1). Are there special reasons for this or doesn't it matter which value you take for X?
Thanks and best regards
Thomas

**Comment by AK-Homberger** [comment]
Hi Thomas,
The only reason is that X=2 worked for me. But it's free software. Feel free to test other values and see if it's working for your AP. 
Regards,
Andreas

**Comment by TomHW** [comment]
Hi Andreas,
thanks for the fast reply. I will rebuild the circuit and test with different settings.
Regards
Thomas
