### ISSUE TITLE
Pro Micro Board has different dimensions

### ISSUE THREAD

**Issue by TomHW** [AK-Homberger/Seatalk-Autopilot-Remote-Control#3]
I ordered a Pro Micro Mini USB Board 5 V from Makershop.de and while assembling the board I discovered that the Pro Micro Board does not fit. It is longer and wider (4.4 × 2.5 × 0.8 cm). One advantage is the better anchoring of the USB socket. However, the Pro Micro Board does not match the current RF board.

Regards
Thomas
![IMG_4945](https://user-images.githubusercontent.com/66836641/99154547-0337fd80-26b1-11eb-9da1-4538353c8f76.jpg)

**Comment by AK-Homberger** [comment]
Many thanks for reporting the issue. I changed the link to a shop with a Pro Micro with the right dimension.
