### ISSUE TITLE
R3 wrong value?

### ISSUE THREAD

**Issue by TomHW** [AK-Homberger/Seatalk-Autopilot-Remote-Control#4]
I built three remote controls and all of them came up with "SendError" in the display. The reason was too high voltage at pin 3 of IC 74LS07. After replacing R3 (27 k) from the voltage divider with 2.7 k everything was fine. Maybe the circuit diagram and the parts list is missing a decimal point?

**Comment by AK-Homberger** [comment]
Hi TomHW,
What do you mean with "too high"?
With 12 V the Voltage on pin 3 should be about 3 Volt which not too high but exactly what it should be. And the Zener Diode 5.1 V would protect the 73LS07 anyway. Can check also the other resistors. 
Regards,
Andreas

Calculation: 12/(10K+68K+27K) = 0.14 mA. And 0.14mA * 27K = 3.08 V.

**Comment by TomHW** [comment]
Hi Andreas,
the low value is the problem. Pulling the Seatalk line to GND gives 1.6 V on pin 3 and the output on pin 4 is on High. With the reduced R3 the voltage on pin 3 is 1.2 V and pin 4 goes down to Low. It's strange and my only explanation for the voltage is the input of the 74LS07.
Regards
Thomas

**Comment by AK-Homberger** [comment]
Hi Thomas,
I can't reproduce the reported effect with my devices. With Seatalk to GND I do have 0,5 V on pin 3. That shows a current of 0.025mA through the then parallel connected resitors R2/R3 (19,3K). That was typical for a devices I build so far. But after a closer look to the datasheet of the 74LS07, I identified that the maximum of IIL (the current from input when pulled to low) is specified with 0,2mA. It looks to me that your 74LS07 is closer to the maximum. If lowering the value of R3 works for you that leave it this way. But my recommendation is to re-calculate all three resistors to have sure high and low levels on pin 3. 
But many thanks for reporting the issue. I will update the description accordingly.
Regards
Andreas

**Comment by TomHW** [comment]
Hi Andreas,
R2/R3 with R3=2k7 and then parallel is 2k6. With 1.2 V there must be a current of 0,46 mA what exceeds the IIL maximum more than twice. But I will keep the current R3 and hope that it is stable over a wider temperature range.
Regards
Thomas
